//! scheduler: bridge to the SWI-Prolog planner.
//!
//! Prolog performs META-level reasoning only: dependency closure, blocking
//! analysis, candidate scoring. It never asserts mathematical truth; the
//! only proof-status facts it ever sees (`status(N, kernel_checked)`) are
//! projections of verifier events handed to it by this bridge.
//!
//! If `swipl` is unavailable, a Rust fallback computes the identical score
//! so development machines without Prolog still plan (parity is tested by
//! prolog/tests/planner_tests.pl on machines that have swipl).

use std::collections::{BTreeMap, BTreeSet};
use std::io::Write as _;
use std::path::Path;
use std::process::Command;

use protocol::NodeState;
use thiserror::Error;

#[derive(Debug, Error)]
pub enum SchedulerError {
    #[error("io: {0}")]
    Io(#[from] std::io::Error),
    #[error("invalid node id (must be [a-z0-9-]+): {0}")]
    BadNodeId(String),
    #[error("swipl failed: {0}")]
    Swipl(String),
    #[error("planner output unparsable: {0}")]
    BadOutput(String),
}

#[derive(Clone, Debug)]
pub struct NodeFact {
    pub id: String,
    pub state: NodeState,
    pub impact: f64,
    pub cost: f64,
    /// ids this node depends on (must be proved first)
    pub depends: Vec<String>,
}

#[derive(Clone, Debug, PartialEq)]
pub struct Candidate {
    pub id: String,
    pub score: f64,
}

fn valid_id(id: &str) -> bool {
    !id.is_empty()
        && id
            .chars()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-')
}

fn prolog_status(state: NodeState) -> &'static str {
    match state {
        NodeState::KernelChecked | NodeState::IndependentlyAudited => "kernel_checked",
        NodeState::NumericallyRefuted | NodeState::FormallyRefuted => "refuted",
        NodeState::Superseded => "superseded",
        _ => "open",
    }
}

/// Render node facts as a consultable Prolog file.
pub fn render_facts(nodes: &[NodeFact]) -> Result<String, SchedulerError> {
    let mut s = String::from("% auto-generated by scheduler crate — do not edit\n");
    for n in nodes {
        if !valid_id(&n.id) {
            return Err(SchedulerError::BadNodeId(n.id.clone()));
        }
        s.push_str(&format!("node('{}').\n", n.id));
        s.push_str(&format!("status('{}', {}).\n", n.id, prolog_status(n.state)));
        s.push_str(&format!("impact('{}', {:.6}).\n", n.id, n.impact));
        s.push_str(&format!("estimated_cost('{}', {:.6}).\n", n.id, n.cost));
        for d in &n.depends {
            if !valid_id(d) {
                return Err(SchedulerError::BadNodeId(d.clone()));
            }
            s.push_str(&format!("depends('{}', '{}').\n", n.id, d));
        }
    }
    Ok(s)
}

pub fn swipl_available() -> bool {
    Command::new("swipl")
        .arg("--version")
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

/// Rank open candidates. Uses the SWI-Prolog planner when available,
/// otherwise the Rust fallback with the identical formula.
pub fn plan(
    prolog_dir: &Path,
    nodes: &[NodeFact],
    top_k: usize,
) -> Result<Vec<Candidate>, SchedulerError> {
    if swipl_available() && prolog_dir.join("planner.pl").exists() {
        plan_swipl(prolog_dir, nodes, top_k)
    } else {
        Ok(plan_fallback(nodes, top_k))
    }
}

fn plan_swipl(
    prolog_dir: &Path,
    nodes: &[NodeFact],
    top_k: usize,
) -> Result<Vec<Candidate>, SchedulerError> {
    let facts = render_facts(nodes)?;
    let mut tmp = tempfile::Builder::new()
        .prefix("rh-facts-")
        .suffix(".pl")
        .tempfile()?;
    tmp.write_all(facts.as_bytes())?;
    let facts_path = tmp.path().to_string_lossy().replace('\'', "");
    let goal = format!("run('{}', {})", facts_path, top_k);
    let out = Command::new("swipl")
        .arg("-q")
        .arg("-s")
        .arg(prolog_dir.join("planner.pl"))
        .arg("-g")
        .arg(&goal)
        .arg("-t")
        .arg("halt")
        .output()?;
    if !out.status.success() {
        return Err(SchedulerError::Swipl(format!(
            "{}\n{}",
            String::from_utf8_lossy(&out.stdout),
            String::from_utf8_lossy(&out.stderr)
        )));
    }
    let stdout = String::from_utf8_lossy(&out.stdout);
    let mut result = Vec::new();
    for line in stdout.lines() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        let mut parts = line.split('\t');
        match (parts.next(), parts.next(), parts.next()) {
            (Some("CANDIDATE"), Some(id), Some(score)) => {
                let score: f64 = score
                    .parse()
                    .map_err(|_| SchedulerError::BadOutput(line.to_string()))?;
                result.push(Candidate {
                    id: id.to_string(),
                    score,
                });
            }
            _ => return Err(SchedulerError::BadOutput(line.to_string())),
        }
    }
    Ok(result)
}

/// Rust fallback with the same scoring as prolog/planner.pl:
///   score = impact * (1 + blocker_reduction) / (1 + cost)
/// where blocker_reduction = number of OPEN nodes transitively depending on
/// the candidate. Cyclic nodes are excluded; nodes are candidates whether or
/// not they are blocked (blocked ⇒ they unblock others when solved — the
/// planner ranks, execution order respects dependencies).
pub fn plan_fallback(nodes: &[NodeFact], top_k: usize) -> Vec<Candidate> {
    let by_id: BTreeMap<&str, &NodeFact> = nodes.iter().map(|n| (n.id.as_str(), n)).collect();
    // reverse edges: dep -> dependents
    let mut dependents: BTreeMap<&str, Vec<&str>> = BTreeMap::new();
    for n in nodes {
        for d in &n.depends {
            dependents.entry(d.as_str()).or_default().push(n.id.as_str());
        }
    }
    let transitive_dependents = |start: &str| -> BTreeSet<&str> {
        let mut seen: BTreeSet<&str> = BTreeSet::new();
        let mut stack: Vec<&str> = dependents.get(start).cloned().unwrap_or_default();
        while let Some(x) = stack.pop() {
            if seen.insert(x) {
                if let Some(more) = dependents.get(x) {
                    stack.extend(more.iter().copied());
                }
            }
        }
        seen
    };
    let is_cyclic = |id: &str| transitive_dependents(id).contains(id);
    let mut scored: Vec<Candidate> = nodes
        .iter()
        .filter(|n| prolog_status(n.state) == "open")
        .filter(|n| !is_cyclic(&n.id))
        .map(|n| {
            let reduction = transitive_dependents(&n.id)
                .into_iter()
                .filter(|d| {
                    by_id
                        .get(d)
                        .is_some_and(|f| prolog_status(f.state) == "open")
                })
                .count() as f64;
            Candidate {
                id: n.id.clone(),
                score: n.impact * (1.0 + reduction) / (1.0 + n.cost),
            }
        })
        .collect();
    scored.sort_by(|a, b| {
        b.score
            .partial_cmp(&a.score)
            .unwrap_or(std::cmp::Ordering::Equal)
            .then_with(|| a.id.cmp(&b.id))
    });
    scored.truncate(top_k);
    scored
}

#[cfg(test)]
mod tests {
    use super::*;

    fn node(id: &str, state: NodeState, impact: f64, cost: f64, deps: &[&str]) -> NodeFact {
        NodeFact {
            id: id.into(),
            state,
            impact,
            cost,
            depends: deps.iter().map(|s| s.to_string()).collect(),
        }
    }

    fn sample() -> Vec<NodeFact> {
        vec![
            // root goal, huge impact but huge cost, depends on lemma-a/b
            node("root", NodeState::Proposed, 10.0, 1000.0, &["lemma-a", "lemma-b"]),
            // lemma-a unblocks root; cheap
            node("lemma-a", NodeState::Elaborated, 3.0, 2.0, &[]),
            // lemma-b unblocks root; expensive
            node("lemma-b", NodeState::Proposed, 3.0, 20.0, &[]),
            // already done
            node("done", NodeState::KernelChecked, 5.0, 1.0, &[]),
        ]
    }

    #[test]
    fn fallback_prefers_cheap_unblocking_lemma() {
        let ranked = plan_fallback(&sample(), 10);
        assert_eq!(ranked[0].id, "lemma-a");
        // kernel-checked nodes are not candidates
        assert!(ranked.iter().all(|c| c.id != "done"));
        // score formula: impact 3 * (1 + 1 dependent open) / (1 + 2) = 2.0
        assert!((ranked[0].score - 2.0).abs() < 1e-9);
    }

    #[test]
    fn fallback_excludes_cycles() {
        let nodes = vec![
            node("a", NodeState::Proposed, 5.0, 1.0, &["b"]),
            node("b", NodeState::Proposed, 5.0, 1.0, &["a"]),
            node("c", NodeState::Proposed, 1.0, 1.0, &[]),
        ];
        let ranked = plan_fallback(&nodes, 10);
        assert_eq!(ranked.len(), 1);
        assert_eq!(ranked[0].id, "c");
    }

    #[test]
    fn facts_rendering_and_id_validation() {
        let facts = render_facts(&sample()).unwrap();
        assert!(facts.contains("status('done', kernel_checked)."));
        assert!(facts.contains("depends('root', 'lemma-a')."));
        let bad = vec![node("Bad'Id", NodeState::Proposed, 1.0, 1.0, &[])];
        assert!(render_facts(&bad).is_err());
    }

    #[test]
    fn swipl_parity_when_available() {
        if !swipl_available() {
            eprintln!("swipl not available; skipping parity test");
            return;
        }
        let prolog_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../prolog");
        if !prolog_dir.join("planner.pl").exists() {
            eprintln!("planner.pl missing; skipping");
            return;
        }
        let nodes = sample();
        let from_prolog = plan_swipl(&prolog_dir, &nodes, 10).unwrap();
        let from_rust = plan_fallback(&nodes, 10);
        assert_eq!(
            from_prolog.iter().map(|c| &c.id).collect::<Vec<_>>(),
            from_rust.iter().map(|c| &c.id).collect::<Vec<_>>()
        );
        for (p, r) in from_prolog.iter().zip(from_rust.iter()) {
            assert!((p.score - r.score).abs() < 1e-4, "{p:?} vs {r:?}");
        }
    }
}
